apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "collabnext_alpha.fullname" . }}-backend
  labels:
    {{- include "collabnext_alpha.labels" . | nindent 4 }}
    app: backend
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "collabnext_alpha.selectorLabels" . | nindent 6 }}
      app: backend
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
        app: backend
      {{- end }}
      labels:
        {{- include "collabnext_alpha.selectorLabels" . | nindent 8 }}
        app: backend
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "collabnext_alpha.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          env:
            - name: FLASK_DEBUG
              value: {{ .Values.backend.env.FLASK_DEBUG  | quote }}
            - name: DB_PASSWORD
              value: {{ .Values.postgresql.auth.postgresPassword }}
            - name: DB_USER
              value:  {{ .Values.postgresql.auth.username }}
            - name: DB_DATABASE
              value: {{ .Values.postgresql.auth.database }}
            - name: DB_HOST
              value: {{ include "collabnext_alpha.fullname" . }}-postgresql
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.port }}
              protocol: TCP
{{/*          livenessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /*/}}
{{/*              port: http*/}}
{{/*          readinessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /*/}}
{{/*              port: http*/}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
