apiVersion: v1
kind: Service
metadata:
  name: {{ include "collabnext_alpha.fullname" . }}-backend
  labels:
    {{- include "collabnext_alpha.labels" . | nindent 4 }}
    app: backend

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "collabnext_alpha.selectorLabels" . | nindent 4 }}
