# Python to Linux Web App on Azure
# Build your Python project and deploy it to Azure as a Linux Web App.
# Change python version to one thats appropriate for your application.
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureServiceConnectionId: 'nsf-cloudbank-azure-connection'

  # Web app name
  webAppName: 'collabnext'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  # Environment name
  environmentName: 'collabnext'

  # Project root folder. Point to the folder containing manage.py file.
  projectRoot: $(System.DefaultWorkingDirectory)

  pythonVersion: '3.11'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Npm@1
      displayName: 'npm install'
      inputs:
        workingDir: '$(System.DefaultWorkingDirectory)/frontend'
        command: 'install'
    - task: Npm@1
      displayName: 'npm install'
      inputs:
        workingDir: '$(System.DefaultWorkingDirectory)/frontend'
        command: 'custom'
        customCommand: 'install --legacy-peer-deps'
    - task: Npm@1
      displayName: 'npm install'
      inputs:
        workingDir: '$(System.DefaultWorkingDirectory)/frontend'
        command: 'custom'
        customCommand: 'install @memgraph/orb'
    - task: Npm@1
      displayName: 'npm build'
      inputs:
        workingDir: '$(System.DefaultWorkingDirectory)/frontend'
        command: 'custom'
        customCommand: 'run build:production'
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
      displayName: 'Use Python $(pythonVersion)'
    - script: |
        python -m venv antenv
        source antenv/bin/activate
        python -m pip install --upgrade pip
        pip install setup
        pip install -r $(System.DefaultWorkingDirectory)/backend/requirements.txt
        rm -rf $(System.DefaultWorkingDirectory)/backend/build
        mkdir $(System.DefaultWorkingDirectory)/backend/build
        cp -r $(System.DefaultWorkingDirectory)/frontend/build/* $(System.DefaultWorkingDirectory)/backend/build
        cp $(System.DefaultWorkingDirectory)/backend/startup.sh $(System.DefaultWorkingDirectory)/backend/
      workingDirectory: $(System.DefaultWorkingDirectory)/backend
      displayName: "Install requirements"
    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/backend'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true
    
    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      displayName: 'Upload package'
      artifact: drop

- stage: Deploy
  displayName: 'Deploy Web App'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentJob
    pool:
      vmImage: $(vmImageName)
    environment: $(environmentName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(pythonVersion)'
            displayName: 'Use Python version'
          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App : collabnext'
            inputs:
              azureSubscription: $(azureServiceConnectionId)
              appName: $(webAppName)
              package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
              startUpCommand: 'sh startup.sh'