app = "collabnext-public-backend"  # unique name

primary_region = "ord"

[build]
  dockerfile = "./docker/Dockerfile.backend"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
