services:
  ###################
  #   FRONTEND (production build)
  ###################
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: collabnext_public_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - collabnext-network
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./frontend/package.json

  ###################
  #   BACKEND
  ###################
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: collabnext_public_backend
    ports:
      - "8000:5000"
    environment:
      FLASK_DEBUG: "0"
      DB_HOST: db
      DB_USER: openalexreader
      DB_PASSWORD: collabnext2024reader!
      DB_NAME: openalex
    depends_on:
      - db
    networks:
      - collabnext-network
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - __pycache__/
        - action: rebuild
          path: ./backend/requirements.txt

  ###################
  #   DATABASE
  ###################
  db:
    build:
      context: ./docker
      dockerfile: Dockerfile.database
    container_name: collabnext_public_db
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - collabnext-network

networks:
  collabnext-network:


volumes:
  db_data:
