services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_BASE_URL=http://localhost:5000
    ports:
      - "3000:8080"
    environment:
      - REACT_APP_BASE_URL=http://localhost:5000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=small_openalex
      - DB_USER=postgres
      - DB_PASSWORD=password
    ports:
      - "5000:5000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
