app = "collabnext-aastika-chinar-dean-public-frontend"
primary_region = "ord"

[build]
  dockerfile = "./frontend/Dockerfile.frontend"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
