# Beyond the traditional .ini files we also have ..toml for those of us who are inclined to utilize test markers to "acquire" subsets of the database search functions without running the whole thing which is a specification of the engineering soul.
[tool.pytest.ini_options]
addopts = """
    -ra -q
    --cov=backend
    --cov-report=term-missing
    --cov-report=html
    --cov-report=xml
    --junitxml=pytest_junit.xml
    --durations=5
"""
testpaths = ["backend/tests"]
markers = [
    "slow: mark test as slow to run",
    "integration: mark test as requiring DB or external resources"
]
