# Default values for collabnext_alpha.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

frontend:
  image:
    repository:  containers.renci.org/frink/collab_next_frontend
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "v0.0.2"
  service:
    port: 8080

backend:
  image:
    repository: containers.renci.org/frink/collab_next_backend
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "v0.0.2"
  service:
    port: 5000
  env:
    FLASK_DEBUG: "0"


postgresql:
  enabled: true
  auth:
    enablePostgresUser: true
    username: openalexreader
    password: "collabnext2024reader!"
    database: "openalex"
  architecture: standalone
  primary:
    resources:
      limits:
        memory: 2Gi
        cpu: 2
    persistence:
      size: 30Gi
      storageClass: "basic"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  pathType: "ImplementationSpecific"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/enable-cors: "true"
  hosts:
     host: collabnext-alpha.apps.renci.org
     paths:
      path: /
      pathType: ImplementationSpecific
  tls:
    - secretName: collabnext-alpha.apps.renci.org-tls
      hosts:
        - collabnext-alpha.apps.renci.org

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
