name: Build and Push Helm Chart

on:
  workflow_dispatch: # Manual trigger only

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-helm-chart:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/helm-chart
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Package Helm chart
        run: |
          cd helm/collabnext_alpha
          helm dependency update
          helm package . --version ${{ steps.meta.outputs.version }} --app-version ${{ steps.meta.outputs.version }}

      - name: Push Helm chart to OCI registry
        run: |
          cd helm/collabnext_alpha
          # Push the chart as an OCI artifact
          helm push collabnext-alpha-${{ steps.meta.outputs.version }}.tgz oci://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/helm-chart
          
          # Also tag as latest if this is the main branch
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            helm push collabnext-alpha-${{ steps.meta.outputs.version }}.tgz oci://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/helm-chart:latest
          fi

      - name: Create Helm chart metadata
        run: |
          # Create a metadata file for easy consumption
          cat > helm-chart-metadata.json << EOF
          {
            "name": "collabnext-alpha",
            "version": "${{ steps.meta.outputs.version }}",
            "repository": "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/helm-chart",
            "images": {
              "backend": "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/backend:latest",
              "frontend": "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/frontend:latest",
              "database": "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/database:latest"
            },
            "deployment": {
              "local": "helm install collabnext-local oci://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/helm-chart --version ${{ steps.meta.outputs.version }} -f values-local.yaml",
              "production": "helm install collabnext-prod oci://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/helm-chart --version ${{ steps.meta.outputs.version }} -f values.yaml"
            }
          }
          EOF
          
          echo "Helm chart metadata:"
          cat helm-chart-metadata.json

      - name: Upload Helm chart metadata
        uses: actions/upload-artifact@v4
        with:
          name: helm-chart-metadata
          path: helm-chart-metadata.json
          retention-days: 30 