name: Make Packages Public

on:
  schedule:
    # Run daily at midnight UTC to catch any packages that weren't made public
    - cron: '0 0 * * *'
  workflow_dispatch: # Allow manual triggering
  workflow_run:
    workflows: ["Build and Push Docker Images"]
    types:
      - completed

jobs:
  make-public:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    
    permissions:
      packages: write
      
    strategy:
      matrix:
        package: [backend, frontend, database]
        
    steps:
      - name: Make package public
        run: |
          # Get the package data
          PACKAGE_DATA=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/orgs/${{ github.repository_owner }}/packages/container/${{ github.repository_name }}%2F${{ matrix.package }}")
          
          # Check if package exists and is private
          if echo "$PACKAGE_DATA" | jq -e '.visibility == "private"' > /dev/null; then
            echo "Making ${{ matrix.package }} package public..."
            curl -X PATCH \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/orgs/${{ github.repository_owner }}/packages/container/${{ github.repository_name }}%2F${{ matrix.package }}" \
              -d '{"visibility":"public"}'
            echo "✅ ${{ matrix.package }} package is now public"
          else
            echo "ℹ️ ${{ matrix.package }} package is already public or doesn't exist yet"
          fi 